// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwfYwFa5bYDtK58XkpcpsBn3RGKEZ6nDA',
    appId: '1:730383670245:web:1d4cb1f44b5f05a6e16d0c',
    messagingSenderId: '730383670245',
    projectId: 'football-21204',
    authDomain: 'football-21204.firebaseapp.com',
    databaseURL: 'https://football-21204-default-rtdb.firebaseio.com',
    storageBucket: 'football-21204.firebasestorage.app',
    measurementId: 'G-TG1KV13YMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB81847HksYt8k6kgc64hbObOAu1OTNZp4',
    appId: '1:730383670245:android:a928842d21dff8cfe16d0c',
    messagingSenderId: '730383670245',
    projectId: 'football-21204',
    databaseURL: 'https://football-21204-default-rtdb.firebaseio.com',
    storageBucket: 'football-21204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLdZsCwPxbsjw04tZAjmxiz6q3xKZm96U',
    appId: '1:730383670245:ios:8558cc62799f8c14e16d0c',
    messagingSenderId: '730383670245',
    projectId: 'football-21204',
    databaseURL: 'https://football-21204-default-rtdb.firebaseio.com',
    storageBucket: 'football-21204.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLdZsCwPxbsjw04tZAjmxiz6q3xKZm96U',
    appId: '1:730383670245:ios:8558cc62799f8c14e16d0c',
    messagingSenderId: '730383670245',
    projectId: 'football-21204',
    databaseURL: 'https://football-21204-default-rtdb.firebaseio.com',
    storageBucket: 'football-21204.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnjdj-uE0LB0dv1f4LrCs2I3GIJ0NrX0g',
    appId: '1:730383670245:web:5968c8971b04a7c7e16d0c',
    messagingSenderId: '730383670245',
    projectId: 'football-21204',
    authDomain: 'football-21204.firebaseapp.com',
    databaseURL: 'https://football-21204-default-rtdb.firebaseio.com',
    storageBucket: 'football-21204.firebasestorage.app',
    measurementId: 'G-6NRGMZ4LBL',
  );
}